#!/usr/bin/bash 
# Name: kevin wong
# File: suffix
# Date: Sat Nov 13 00:15:30 PST 2021
# Desc: renames a file by appending a "." followed by argument passed to the file name

echo "# your file $1 has been renamed to $1$2"
mv $1 /tmp/$1
mv /tmp/$1 $1$2
